name: Shiny Clean Sounds
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6678
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: 'Shiny Clean Sounds: Sound Editorial & Design'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#d93f2b'
    - '#747474'
    - '#fcba45'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
