name: Shiny Clean Sounds
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6678
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#797979'
    - '#b0b0b0'
    - '#dc452a'
  brandStrength: 1
  lightness: 0.3152524
  saturation: 0.7019334
  rhythmicContrast: 0.4280344
purpose: []
